name = "HouseCompanyEnergyModel"
uuid = "d788abea-2135-46a1-b5e7-aa5d7f874e83"
authors = ["Helmi Hankimaa <helmi.hankimaa@gmail.com>"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"